// Level 1 retrieval. Loads the corpus from a single JSON file (swapping the
// corpus = replacing that file), embeds each chunk once via Mistral Embed, caches
// the vectors in memory, and ranks by cosine similarity. No vector DB dependency.
import fs from "fs";
import path from "path";
import { MODELS, mistral, recordUsage, withLimit } from "./client";

export interface Chunk {
  id: string;
  title: string;
  url: string;
  text: string;
  language?: string;
  topic?: string;
  // Names the in-assistant action this content describes (if any). The knowledge
  // base can't know the assistant exists - this tag is the join between the
  // content registry and the action registry. Code renders the affordance; the
  // model never advertises capabilities.
  relatedAction?: "lock_card" | "unlock_card";
}

export interface RetrievalHit {
  chunk: Chunk;
  score: number;
}

interface Corpus {
  version: string;
  note?: string;
  chunks: Chunk[];
}

interface PrebuiltIndex {
  model: string;
  dim: number;
  version: string;
  vectors: { id: string; vector: number[] }[];
}

const CORPUS_FILE = path.join(process.cwd(), "data", "faq-corpus.json");
const INDEX_FILE = path.join(process.cwd(), "data", "faq-index.json");

let corpusCache: Corpus | null = null;
let vectorCache: { id: string; vector: number[] }[] | null = null;
let embedPromise: Promise<void> | null = null;

function loadCorpus(): Corpus {
  if (corpusCache) return corpusCache;
  corpusCache = JSON.parse(fs.readFileSync(CORPUS_FILE, "utf-8")) as Corpus;
  return corpusCache;
}

export function getCorpusMeta(): { version: string; count: number } {
  const c = loadCorpus();
  return { version: c.version, count: c.chunks.length };
}

function cosine(a: number[], b: number[]): number {
  let dot = 0;
  let na = 0;
  let nb = 0;
  for (let i = 0; i < a.length; i++) {
    dot += a[i] * b[i];
    na += a[i] * a[i];
    nb += b[i] * b[i];
  }
  return na && nb ? dot / (Math.sqrt(na) * Math.sqrt(nb)) : 0;
}

// Load the COMMITTED pre-built vector index so clone-and-run needs no ingestion.
// The index is generated by `npm run setup` and committed to data/faq-index.json.
// Only if it is missing (or stale vs the corpus) do we re-embed the whole corpus
// lazily at first query. Either way, only the QUERY is embedded per request.
async function ensureEmbedded(): Promise<void> {
  if (vectorCache) return;
  if (embedPromise) return embedPromise;
  embedPromise = (async () => {
    const corpus = loadCorpus();
    const corpusIds = new Set(corpus.chunks.map((c) => c.id));

    if (fs.existsSync(INDEX_FILE)) {
      try {
        const index = JSON.parse(fs.readFileSync(INDEX_FILE, "utf-8")) as PrebuiltIndex;
        const indexed = index.vectors.filter((v) => corpusIds.has(v.id));
        // Use the committed index only if it covers every current chunk.
        if (indexed.length === corpus.chunks.length) {
          vectorCache = indexed;
          return;
        }
        console.warn(`[retrieval] index covers ${indexed.length}/${corpus.chunks.length} chunks; re-embedding.`);
      } catch (err) {
        console.warn("[retrieval] could not read committed index, re-embedding:", err);
      }
    }

    const inputs = corpus.chunks.map((c) => `${c.title}\n${c.text}`);
    const res = await mistral.embeddings.create({ model: MODELS.embed, inputs });
    vectorCache = res.data.map((d, i) => ({ id: corpus.chunks[i].id, vector: d.embedding as number[] }));
  })();
  // Self-heal: if the corpus embed fails, DON'T leave a rejected promise cached
  // (every future retrieve() would then reject forever until a process restart).
  // Clear it so the next call retries from scratch.
  embedPromise.catch(() => {
    embedPromise = null;
  });
  return embedPromise;
}

export async function retrieve(query: string, k = 3): Promise<RetrievalHit[]> {
  await ensureEmbedded();
  const corpus = loadCorpus();
  let qres;
  try {
    qres = await withLimit(() => mistral.embeddings.create({ model: MODELS.embed, inputs: [query] }));
  } catch (err) {
    // Make an embed OUTAGE distinct from a genuine low-similarity miss. Both would
    // otherwise surface as the same "no grounded source" refusal - impossible to
    // tell apart in the logs. Log it and rethrow so the route degrades cleanly
    // ("service busy") rather than falsely claiming the corpus has no answer.
    const status = (err as { statusCode?: number })?.statusCode;
    console.error(`[retrieval] query embed failed${status ? ` (${status})` : ""} - degrading, not a real miss`);
    throw err;
  }
  recordUsage(MODELS.embed, qres.usage);
  const qvec = qres.data[0].embedding as number[];

  const scored = (vectorCache ?? []).map((v) => {
    const chunk = corpus.chunks.find((c) => c.id === v.id)!;
    return { chunk, score: cosine(qvec, v.vector) };
  });
  scored.sort((a, b) => b.score - a.score);
  return scored.slice(0, k);
}
